#! /bin/sh

# helm.bin is the original helm binary
case $1 in
  show*)
    exec /usr/local/bin/helm.bin $@
    ;;
  template*)
    exec /usr/local/bin/helm.bin secrets $@ | grep -ve '^removed .*$'
    # exec /usr/local/bin/helm.bin secrets $@ | head -n -1 -
    ;;
  *)
    exec /usr/local/bin/helm.bin secrets $@
    ;;
esac
